### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by scaires** [scaires/CTS#55]
- [ ] Copy to release repo
- [ ] Link GIFs (of just CTS, no gameplay)
- [ ] Link how-to-play video
- [ ] Create community hub post
- [ ] Create Reddit post
- [ ] Create Spectrum post
- [ ] Create screenshots
